version: '3.2'
services:
  calculator:
      image: devopsdockeruh/scaling-exercise-calculator
      ports:
        - 3000:3000
      container_name: calculator
  compute:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=compute.localtest.me


  scaledcompute1:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=scaledcompute1.localtest.me

  scaledcompute2:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=scaledcompute2.localtest.me

  scaledcompute3:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=scaledcompute3.localtest.me

  scaledcompute4:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=scaledcompute4.localtest.me

  scaledcompute5:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=scaledcompute5.localtest.me

  load-balancer:
      build: ./load-balancer
      image: load-balancer
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      container_name: load-balancer
