
version: '3'

services:
        simple-web-service:
                image: devopsdockeruh/simple-web-service:alpine

                container_name: web-service

                ports:
                        - 8080:8080
                command: bundle exec server 

