
version: '3'

services:
        nginx-proxy:
                image: jwilder/nginx-proxy
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf
                        - /var/run/docker.sock:/tmp/docker.sock:ro
                ports:
                        - 80:80
                environment:
                           - NGINX_HOST=localhost
        frontend:
                container_name: frontend-service
                build:
                        context: ./example-frontend
                        dockerfile: Dockerfile-2.3_frontend
                ports:
                        - 5000:5000
        backend:
                container_name: backend-service
                build:
                        context: ./example-backend
                        dockerfile: Dockerfile-2.3_backend 
                ports:
                        - 8080:8080

                environment:
                        - REDIS_HOST=redis
                        - POSTGRES_HOST=postgresdb
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWD=postgres
                        - POSTGRES_DATABASE=postgres
        redis:
                image: redis:6

                container_name: redis

                hostname: redis

                restart: unless-stopped

        db:
                image: postgres:13.2-alpine
                restart: unless-stopped
                environment:
                        POSTGRES_PASSWORD: postgres
                container_name: postgres_db
                hostname: postgresdb

