
version: '3'

services:
        frontend:
                container_name: frontend-service
                build:
                        context: ./example-frontend
                        dockerfile: Dockerfile-2.3_frontend
                ports:
                        - 5000:5000
        backend:
                container_name: backend-service
                build:
                        context: ./example-backend
                        dockerfile: Dockerfile-2.3_backend 
                ports:
                        - 8080:8080

                environment:
                        - REDIS_HOST=redis
        redis:
                image: redis:6

                container_name: redis

                hostname: redis

                restart: unless-stopped


